### ISSUE TITLE
Standalone language server

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#351]
> a.k.a Wen VIM?

Support the use of the language server component outside of vscode, so it can be leveraged by other editors, initially targeting vim and neovim.

## Status - Experimental

We have released an experimental **vim-coc** extension that wraps the language server. It can be installed from here: https://www.npmjs.com/package/@ignored/coc-solidity

## Subissues

* https://github.com/NomicFoundation/hardhat-vscode/issues/68
* https://github.com/NomicFoundation/hardhat-vscode/issues/341
* https://github.com/NomicFoundation/hardhat-vscode/issues/320
* https://github.com/NomicFoundation/hardhat-vscode/issues/437

## Release Checklist

* [x] Add docs for setup and configuring the language server for vim-coc
* [x] Add docs for setup and config for neovim
* [x] Check analytics meets privacy policy
* [x] Add a small note to the EXTENSION.md indicating there are equivalents for other editors
* [x] move the language server and vim-coc extension to the `@nomicfoundation` namespace 
* [ ] Add links to popular vim/nvim repos like:
  - [ ] lspconfig
  - [x] mason
  - [ ] others?

**Comment by Handfish** [comment]
+1 for Mason

**Comment by pyk** [comment]
@kanej is there a way to set the `formatter` with the nvim lsp?

I use the following config but it ignores the `forge fmt`:

```
  solidity_ls_nomicfoundation = {
    settings = {
      solidity = {
        formatter = { "forge" }      
      }
    }
  },

```
