### ISSUE TITLE
Developer framework agnostic

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-vscode#352]
The **Solidity by Nomic Foundation** vscode extension should work across the most popular solidity development frameworks (not just **Hardhat**).

We are refactoring the internals to isolate Hardhat specific logic behind an adapter, so that alternate adapters for truffle, foundry etc can be developed.

This will allow core editor features like navigation, diagnostics and quickfixes to be used across different projects.

## Status - experimental

Experimental support for foundry projects was released as part of `v0.6.0`.

## Subissues

* https://github.com/NomicFoundation/hardhat-vscode/pull/278
* https://github.com/NomicFoundation/hardhat-vscode/issues/45
* https://github.com/NomicFoundation/hardhat-vscode/issues/46
* https://github.com/NomicFoundation/hardhat-vscode/issues/47
* https://github.com/NomicFoundation/hardhat-vscode/issues/391
* https://github.com/NomicFoundation/hardhat-vscode/issues/338

## Release checklist

* [ ] Update docs with
  - [ ] Section explaining projects within the extension
  - [ ] guide to foundry projects (using fmt and remappings)
